export const routes = [
    {
        id: 1,
        name: "Home",
        path: "/",
        type: "collapse",
        subRoutes: [],
    },
    {
        id: 2,
        name: "About Us",
        type: "collapse",
        path: "/about-us",
        subRoutes: [],
    },
    {
        id: 3,
        name: "Services",
        type: "collapse",
        path: "/services",
        subRoutes: [
            {
                id: 1,
                name: "Cleaning Services",
                type: "collapse",
                path: "/cleaning",
                subRoutes: [
                    {
                        id: 1,
                        name: "Pressure Washing",
                        type: "collapse",
                        path: "/cleaning/services/pressure-washing",
                        subRoutes: [],
                    },
                    {
                        id: 2,
                        name: "Window Cleaning",
                        type: "collapse",
                        path: "/cleaning/services/window-cleaning",
                        subRoutes: [],
                    },
                    // {
                    //     id: 3,
                    //     name: "Commercial",
                    //     type: "collapse",
                    //     path: "/cleaning/services/commercial",
                    //     subRoutes: [],
                    // },
                    {
                        id: 4,
                        name: "Restaurant",
                        type: "collapse",
                        path: "/cleaning/services/restaurant",
                        subRoutes: [],
                    },
                    {
                        id: 5,
                        name: "Residential",
                        type: "collapse",
                        path: "/cleaning/services/residential",
                        subRoutes: [],
                    },
                ],
            },
            {
                id: 2,
                name: "Landscaping Services",
                type: "collapse",
                path: "/landscaping",
                subRoutes: [
                    {
                        id: 1,
                        name: "Concrete",
                        type: "collapse",
                        path: "/landscaping/services/concrete",
                        subRoutes: [],
                    },
                    {
                        id: 2,
                        name: "Landscaping",
                        type: "collapse",
                        path: "/landscaping/services/landscaping",
                        subRoutes: [],
                    },
                    {
                        id: 3,
                        name: "Interlocking",
                        type: "collapse",
                        path: "/landscaping/services/interlocking",
                        subRoutes: [],
                    },
                    {
                        id: 4,
                        name: "Sod Installation / Grading",
                        type: "collapse",
                        path: "/landscaping/services/sod-installation-grading",
                        subRoutes: [],
                    },
                    {
                        id: 5,
                        name: "Fencing And Decking",
                        type: "collapse",
                        path: "/landscaping/services/fencing-and-decking",
                        subRoutes: [],
                    },
                    {
                        id: 6,
                        name: "Residential And Commercial Maintenance",
                        type: "collapse",
                        path: "/landscaping/services/residential-and-commercial-maintenance",
                        subRoutes: [],
                    },
                    {
                        id: 7,
                        name: "Snow Removal",
                        type: "collapse",
                        path: "/landscaping/services/snow-removal",
                        subRoutes: [],
                    },
                    {
                        id: 8,
                        name: "Artificial grass",
                        type: "collapse",
                        path: "/landscaping/services/artificial-grass",
                        subRoutes: [],
                    },
                ],
            },
        ],
    },
    {
        id: 4,
        name: "Clients",
        type: "collapse",
        path: "/clients",
        subRoutes: [],
    },
    {
        id: 5,
        name: "Contact Us",
        type: "collapse",
        path: "/contact-us",
        subRoutes: [],
    },
];
export const landingPagesRoutes = [
    {
        id: 1,
        name: "Home",
        path: "/",
        type: "collapse",
        subRoutes: [],
    },
    {
        id: 2,
        name: "About Us",
        type: "collapse",
        path: "/about-us",
        subRoutes: [],
    },
    {
        id: 3,
        name: "Contact Us",
        type: "collapse",
        path: "/contact-us",
        subRoutes: [],
    },
];
